export type LocaleCode='en'|'es'|'pt'|'fr'|'de'|'zh-CN'|'ar'|'it'|'ru'|'uk'|'be'|'ja'|'ko';
export const defaultLocale:LocaleCode='en';
export const localeRegistry={en:{code:'en',label:'English',dir:'ltr',marketDefault:'US',currencyDefault:'USD',enabled:true,fontStrategy:'latin'},es:{code:'es',label:'Español',dir:'ltr',marketDefault:'ES',currencyDefault:'EUR',enabled:true,fontStrategy:'latin'},pt:{code:'pt',label:'Português',dir:'ltr',marketDefault:'PT',currencyDefault:'EUR',enabled:true,fontStrategy:'latin'},fr:{code:'fr',label:'Français',dir:'ltr',marketDefault:'FR',currencyDefault:'EUR',enabled:true,fontStrategy:'latin'},de:{code:'de',label:'Deutsch',dir:'ltr',marketDefault:'DE',currencyDefault:'EUR',enabled:true,fontStrategy:'latin'}} as const;
export const localeRegistry2={'zh-CN':{code:'zh-CN',label:'简体中文',dir:'ltr',marketDefault:'CN',currencyDefault:'CNY',enabled:true,fontStrategy:'cjk'},ar:{code:'ar',label:'العربية',dir:'rtl',marketDefault:'AE',currencyDefault:'AED',enabled:true,fontStrategy:'arabic'},it:{code:'it',label:'Italiano',dir:'ltr',marketDefault:'IT',currencyDefault:'EUR',enabled:true,fontStrategy:'latin'},ru:{code:'ru',label:'Русский',dir:'ltr',marketDefault:'RU',currencyDefault:'EUR',enabled:true,fontStrategy:'cyrillic'},uk:{code:'uk',label:'Українська',dir:'ltr',marketDefault:'UA',currencyDefault:'EUR',enabled:true,fontStrategy:'cyrillic'},be:{code:'be',label:'Беларуская',dir:'ltr',marketDefault:'BY',currencyDefault:'EUR',enabled:true,fontStrategy:'cyrillic'},ja:{code:'ja',label:'日本語',dir:'ltr',marketDefault:'JP',currencyDefault:'JPY',enabled:true,fontStrategy:'cjk'},ko:{code:'ko',label:'한국어',dir:'ltr',marketDefault:'KR',currencyDefault:'KRW',enabled:true,fontStrategy:'cjk'}} as const;
export const locales={...localeRegistry,...localeRegistry2};
export const localeCodes=Object.keys(locales) as LocaleCode[];
export const isLocaleCode=(v:string):v is LocaleCode=>v in locales;
export const filterDefinitions=[{id:'price',label:'Price',kind:'range'},{id:'stops',label:'Stops',kind:'multi-select'},{id:'baggage',label:'Baggage',kind:'toggle'},{id:'airlines',label:'Airlines',kind:'multi-select'},{id:'airports',label:'Airports',kind:'multi-select'},{id:'self-transfer',label:'Self-transfer',kind:'toggle'}] as const;
export const scenarioConfigs={standard:{type:'standard',label:'Standard',description:'Balanced default.',defaultSort:'best',rankingWeights:{price:.28,duration:.22,stops:.18},visibleFilters:['price','stops','baggage','airlines'],copyHint:'Balanced default search.'},cheapest:{type:'cheapest',label:'Cheapest',description:'Price first.',defaultSort:'price',rankingWeights:{price:.56,duration:.08,stops:.12},visibleFilters:['price','stops','self-transfer'],copyHint:'Budget-focused search.'},best:{type:'best',label:'Best',description:'Quality and price.',defaultSort:'best',rankingWeights:{price:.24,duration:.2,stops:.18},visibleFilters:['price','stops','baggage'],copyHint:'Most balanced quality option.'},weekend:{type:'weekend',label:'Weekend',description:'Short-trip optimized.',defaultSort:'duration',rankingWeights:{price:.22,duration:.32,stops:.18},visibleFilters:['price','stops'],copyHint:'Short getaway mode.'}}
export const scenarioConfigsExtra={family:{type:'family',label:'Family',description:'Comfort and baggage.',defaultSort:'best',rankingWeights:{price:.2,duration:.18,stops:.24},visibleFilters:['price','stops','baggage','airports'],copyHint:'Fewer frictions for families.'},business:{type:'business',label:'Business',description:'Schedule quality first.',defaultSort:'departure',rankingWeights:{price:.12,duration:.24,stops:.22},visibleFilters:['stops','airlines'],copyHint:'Time-sensitive traveler mode.'}}
export const scenarioConfigsLast={'direct-priority':{type:'direct-priority',label:'Direct priority',description:'Nonstop-first ranking.',defaultSort:'best',rankingWeights:{price:.18,duration:.22,stops:.32},visibleFilters:['stops','airlines','airports'],copyHint:'Prefer nonstop routes.'}};
export const queueNames=['search-refresh','price-alerts','clickout-events','provider-sync','seo-precompute','translations-sync','analytics-rollups','notifications'] as const;
export const localeList=Object.values(locales);
export const scenarios={...scenarioConfigs,...scenarioConfigsExtra,...scenarioConfigsLast};
