import*as React from'react';import{cn,formatDuration}from'@flyntos/shared';
export const PageContainer=({className,children}:{className?:string;children:React.ReactNode})=><div className={cn('mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',className)}>{children}</div>;
export const Section=({className,children}:{className?:string;children:React.ReactNode})=><section className={cn('py-10 sm:py-16',className)}>{children}</section>;
export const Card=({className,children}:{className?:string;children:React.ReactNode})=><div className={cn('rounded-3xl border border-white/12 bg-white/6 shadow-[0_24px_80px_rgba(3,7,18,.45)] backdrop-blur-xl',className)}>{children}</div>;
export const Button=({className,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>)=><button className={cn('inline-flex items-center justify-center rounded-2xl bg-[linear-gradient(135deg,#7c91ff,#51d2c5)] px-5 py-3 text-sm font-semibold text-slate-950 shadow-[0_0_40px_rgba(81,210,197,.25)] transition hover:scale-[1.01] disabled:opacity-60',className)} {...props}>{children}</button>;
export const Input=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(({className,...props},ref)=><input ref={ref} className={cn('h-12 w-full rounded-2xl border border-white/12 bg-slate-950/40 px-4 text-sm text-white placeholder:text-slate-400 outline-none transition focus:border-cyan-300/50 focus:ring-2 focus:ring-cyan-300/20',className)} {...props}/>);Input.displayName='Input';
export const Badge=({children}:{children:React.ReactNode})=><span className='inline-flex rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs uppercase tracking-[0.24em] text-cyan-100'>{children}</span>;
export const Skeleton=({className}:{className?:string})=><div className={cn('animate-pulse rounded-2xl bg-white/8',className)}/>;
export const EmptyState=({title,description}:{title:string;description:string})=><Card className='p-8 text-center'><h3 className='text-xl font-semibold text-white'>{title}</h3><p className='mt-2 text-sm text-slate-300'>{description}</p></Card>;
